spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG